# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets… secret
# >/
# <>/' Copyright 2023–present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */

# Default values for rest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

livenessPort: 8085

environments:
 - name: SPIFFE_ENDPOINT_SOCKET
   value: "unix:///spire-agent-socket/agent.sock"
 - name: VSECM_LOG_LEVEL
   value: "3"
 - name: VSECM_PROBE_LIVENESS_PORT
   value: ":8085"
 - name: VSECM_SAFE_ENDPOINT_URL
   value: "https://vsecm-safe.vsecm-system.svc.cluster.local:8443/"
 - name: VSECM_SAFE_SPIFFEID_PREFIX
   value: "spiffe://vsecm.com/workload/vsecm-safe/ns/vsecm-system/sa/vsecm-safe/n/"
 - name: VSECM_SAFE_TLS_PORT
   value: ":8443"
 - name: VSECM_SENTINEL_INIT_COMMAND_PATH
   value: "/opt/vsecm-rest/init/data"
 - name: VSECM_SENTINEL_INIT_COMMAND_TOMBSTONE_PATH
   value: "/opt/vsecm-rest/tombstone/init"
 - name: VSECM_SENTINEL_LOGGER_URL
   value: "localhost:50051"
 - name: VSECM_SENTINEL_SECRET_GENERATION_PREFIX
   value: "gen:"
 - name: VSECM_SENTINEL_SPIFFEID_PREFIX
   value: "spiffe://vsecm.com/workload/vsecm-sentinel/ns/vsecm-system/sa/vsecm-sentinel/n/"
 - name: VSECM_SAFE_OIDC_PROVIDER_BASE_URL
   value: "http://0.0.0.0:8080/auth/realms/XXXX/protocol/openid-connect/token/introspect"
 - name: VSECM_SAFE_ENABLE_OIDC_RESOURCE_SERVER
   value: "false"
 - name: VSECM_REST_SPIFFEID_PREFIX
   value: "spiffe://vsecm.com/workload/vsecm-rest/ns/vsecm-system/sa/vsecm-rest/n/"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "vsecm-rest"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

initCommand:
  enabled: true

  #  Add any initialization command here, separated by a line with only "--"
  command: |
    sleep:1
    --

  #  Example:
  #  ––––––––
  #
  #  sleep:30000
  #  --
  #  w:k8s:keycloak-admin-secret
  #  n:smo-app
  #  s:gen:{"username":"admin-[a-z0-9]{6}","password":"[a-zA-Z0-9]{12}"}
  #  t:{"KEYCLOAK_ADMIN_USER":"{{.username}}","KEYCLOAK_ADMIN_PASSWORD":"{{.password}}"}
  #  --
  #  w:k8s:keycloak-db-secret
  #  n:smo-app
  #  s:gen:{"username":"admin-[a-z0-9]{6}","password":"[a-zA-Z0-9]{12}"}
  #  t:{"KEYCLOAK_DB_USER":"{{.username}}","KEYCLOAK_DB_PASSWORD":"{{.password}}"}
  #  --
  #  sleep:5000
  #  --
  #  w:keycloak
  #  n:default
  #  s:trigger-init
  #  --
